version: "3.7"

services:
  app:
    container_name: job-finder-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "8000:8000"
    volumes:
    - .:/job-finder-backend
    command: ./entrypoint.sh
    restart: on-failure
