version: "3.7"

services:
  app:
    container_name: job-finder-backend
    build:
      context: .
    ports:
    - "8000:8000"
    volumes:
    - .:/job-finder-backend
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    restart: on-failure
